In [195]:
import pandas as pd
import numpy as np

from numpy import *

In [9]:
lst = pd.read_csv('test.csv')
lst

              date_time  winner_id  winner_bid_price_adv_currency
0   2017-12-22 00:00:00        165                       0.001250
1   2017-12-22 00:00:02         32                       0.001000
2   2017-12-22 00:00:03          1                       0.001000
3   2017-12-22 00:00:03          2                       0.001250
4   2017-12-22 00:00:03        212                       0.001250
5   2017-12-22 00:00:09         26                       0.001250
6   2017-12-22 00:00:09         44                       0.002500
7   2017-12-22 00:00:10         13                       0.012500
8   2017-12-22 00:00:10         44                       0.001250
9   2017-12-22 00:00:10        202                       0.002500
10  2017-12-22 00:00:11         13                       0.001250
11  2017-12-22 00:00:11         54                       0.140000
12  2017-12-22 00:00:11         83                       0.001250
13  2017-12-22 00:00:13         20                       0.001000
14  2017-12-22 00:00:17        177                       0.001250
15  2017-12-22 00:00:18          5                       0.001000
16  2017-12-22 00:00:21         32                       0.001250
17  2017-12-22 00:00:24        219                       0.001250
18  2017-12-22 00:00:28        165                       0.001250
19  2017-12-22 00:00:30         81                       0.000013
20  2017-12-22 00:00:30         81                       0.001000
21  2017-12-22 00:00:30         82                       0.001250
22  2017-12-22 00:00:35          2                       0.002000
23  2017-12-22 00:00:36        176                       0.001250
24  2017-12-22 00:00:37        215                       0.001250
25  2017-12-22 00:00:38         13                       0.012500
26  2017-12-22 00:00:38         44                       0.001250
27  2017-12-22 00:00:38        202                       0.002500
28  2017-12-22 00:00:39         13                       0.001250
29  2017-12-22 00:00:39         54                       0.140000
..                  ...        ...                            ...
70  2017-12-22 00:01:54         54                       0.001000
71  2017-12-22 00:01:57         32                       0.001250
72  2017-12-22 00:02:00          2                       0.001000
73  2017-12-22 00:02:01        112                       0.001250
74  2017-12-22 00:02:02         81                       0.001250
75  2017-12-22 00:02:06         26                       0.000013
76  2017-12-22 00:02:11        112                       0.000125
77  2017-12-22 00:02:12         30                       0.001250
78  2017-12-22 00:02:17         84                       0.001000
79  2017-12-22 00:02:22         48                       0.001000
80  2017-12-22 00:02:25         26                       0.001250
81  2017-12-22 00:02:25         44                       0.002500
82  2017-12-22 00:02:26         83                       0.002500
83  2017-12-22 00:02:27         83                       0.001111
84  2017-12-22 00:02:28          2                       0.001000
85  2017-12-22 00:02:29        112                       0.001250
86  2017-12-22 00:02:33        177                       0.001250
87  2017-12-22 00:02:34          5                       0.001000
88  2017-12-22 00:02:38         83                       0.003750
89  2017-12-22 00:02:39        112                       0.000125
90  2017-12-22 00:02:40        219                       0.001250
91  2017-12-22 00:02:44        165                       0.001250
92  2017-12-22 00:02:46         32                       0.001000
93  2017-12-22 00:02:47          1                       0.001000
94  2017-12-22 00:02:47          2                       0.001250
95  2017-12-22 00:02:47        212                       0.001250
96  2017-12-22 00:02:51          2                       0.002000
97  2017-12-22 00:02:52        176                       0.001250
98  2017-12-22 00:02:53        215                       0.001250
99  2017-12-22 00:02:54         44                       0.001250

[100 rows x 3 columns]

In [64]:
lst[lst['winner_id']==2]['winner_bid_price_adv_currency'].shape
test = lst.as_matrix()
test

array([['2017-12-22 00:00:00', 165, 0.00125],
       ['2017-12-22 00:00:02', 32, 0.001],
       ['2017-12-22 00:00:03', 1, 0.001],
       ['2017-12-22 00:00:03', 2, 0.00125],
       ['2017-12-22 00:00:03', 212, 0.00125],
       ['2017-12-22 00:00:09', 26, 0.00125],
       ['2017-12-22 00:00:09', 44, 0.0025],
       ['2017-12-22 00:00:10', 13, 0.0125],
       ['2017-12-22 00:00:10', 44, 0.00125],
       ['2017-12-22 00:00:10', 202, 0.0025],
       ['2017-12-22 00:00:11', 13, 0.00125],
       ['2017-12-22 00:00:11', 54, 0.14],
       ['2017-12-22 00:00:11', 83, 0.00125],
       ['2017-12-22 00:00:13', 20, 0.001],
       ['2017-12-22 00:00:17', 177, 0.00125],
       ['2017-12-22 00:00:18', 5, 0.001],
       ['2017-12-22 00:00:21', 32, 0.00125],
       ['2017-12-22 00:00:24', 219, 0.00125],
       ['2017-12-22 00:00:28', 165, 0.00125],
       ['2017-12-22 00:00:30', 81, 1.25e-05],
       ['2017-12-22 00:00:30', 81, 0.001],
       ['2017-12-22 00:00:30', 82, 0.00125],
       ['2017-12-22 00:00:35', 2, 0.002],
       ['2017-12-22 00:00:36', 176, 0.00125],
       ['2017-12-22 00:00:37', 215, 0.00125],
       ['2017-12-22 00:00:38', 13, 0.0125],
       ['2017-12-22 00:00:38', 44, 0.00125],
       ['2017-12-22 00:00:38', 202, 0.0025],
       ['2017-12-22 00:00:39', 13, 0.00125],
       ['2017-12-22 00:00:39', 54, 0.14],
       ['2017-12-22 00:00:39', 83, 0.00125],
       ['2017-12-22 00:00:40', 30, 0.001],
       ['2017-12-22 00:00:43', 216, 0.001333333],
       ['2017-12-22 00:00:46', 54, 0.001],
       ['2017-12-22 00:00:49', 32, 0.00125],
       ['2017-12-22 00:00:58', 81, 1.25e-05],
       ['2017-12-22 00:00:58', 81, 0.001],
       ['2017-12-22 00:00:58', 82, 0.00125],
       ['2017-12-22 00:01:02', 83, 0.00375],
       ['2017-12-22 00:01:04', 30, 0.00125],
       ['2017-12-22 00:01:09', 84, 0.001],
       ['2017-12-22 00:01:10', 32, 0.001],
       ['2017-12-22 00:01:11', 1, 0.001],
       ['2017-12-22 00:01:11', 2, 0.00125],
       ['2017-12-22 00:01:11', 212, 0.00125],
       ['2017-12-22 00:01:17', 26, 0.00125],
       ['2017-12-22 00:01:17', 44, 0.0025],
       ['2017-12-22 00:01:18', 83, 0.0025],
       ['2017-12-22 00:01:19', 83, 0.0011111110000000001],
       ['2017-12-22 00:01:21', 20, 0.001],
       ['2017-12-22 00:01:25', 177, 0.00125],
       ['2017-12-22 00:01:26', 5, 0.001],
       ['2017-12-22 00:01:28', 83, 0.001],
       ['2017-12-22 00:01:32', 219, 0.00125],
       ['2017-12-22 00:01:35', 55, 0.001],
       ['2017-12-22 00:01:36', 164, 0.001],
       ['2017-12-22 00:01:36', 165, 0.00125],
       ['2017-12-22 00:01:39', 1, 0.001],
       ['2017-12-22 00:01:39', 2, 0.00125],
       ['2017-12-22 00:01:39', 212, 0.00125],
       ['2017-12-22 00:01:43', 2, 0.002],
       ['2017-12-22 00:01:44', 176, 0.00125],
       ['2017-12-22 00:01:45', 215, 0.00125],
       ['2017-12-22 00:01:46', 13, 0.0125],
       ['2017-12-22 00:01:46', 44, 0.00125],
       ['2017-12-22 00:01:46', 202, 0.0025],
       ['2017-12-22 00:01:47', 13, 0.00125],
       ['2017-12-22 00:01:47', 83, 0.00125],
       ['2017-12-22 00:01:49', 20, 0.001],
       ['2017-12-22 00:01:51', 216, 0.001333333],
       ['2017-12-22 00:01:54', 54, 0.001],
       ['2017-12-22 00:01:57', 32, 0.00125],
       ['2017-12-22 00:02:00', 2, 0.001],
       ['2017-12-22 00:02:01', 112, 0.00125],
       ['2017-12-22 00:02:02', 81, 0.00125],
       ['2017-12-22 00:02:06', 26, 1.25e-05],
       ['2017-12-22 00:02:11', 112, 0.000125],
       ['2017-12-22 00:02:12', 30, 0.00125],
       ['2017-12-22 00:02:17', 84, 0.001],
       ['2017-12-22 00:02:22', 48, 0.001],
       ['2017-12-22 00:02:25', 26, 0.00125],
       ['2017-12-22 00:02:25', 44, 0.0025],
       ['2017-12-22 00:02:26', 83, 0.0025],
       ['2017-12-22 00:02:27', 83, 0.0011111110000000001],
       ['2017-12-22 00:02:28', 2, 0.001],
       ['2017-12-22 00:02:29', 112, 0.00125],
       ['2017-12-22 00:02:33', 177, 0.00125],
       ['2017-12-22 00:02:34', 5, 0.001],
       ['2017-12-22 00:02:38', 83, 0.00375],
       ['2017-12-22 00:02:39', 112, 0.000125],
       ['2017-12-22 00:02:40', 219, 0.00125],
       ['2017-12-22 00:02:44', 165, 0.00125],
       ['2017-12-22 00:02:46', 32, 0.001],
       ['2017-12-22 00:02:47', 1, 0.001],
       ['2017-12-22 00:02:47', 2, 0.00125],
       ['2017-12-22 00:02:47', 212, 0.00125],
       ['2017-12-22 00:02:51', 2, 0.002],
       ['2017-12-22 00:02:52', 176, 0.00125],
       ['2017-12-22 00:02:53', 215, 0.00125],
       ['2017-12-22 00:02:54', 44, 0.00125]], dtype=object)

In [300]:
class Adnw:
    def __init__(self, id, price = None):
        self.id = id
        self.price = []
    
    def set_price(self, lst):
        tmp = lst[lst['winner_id']==self.id]['winner_bid_price_adv_currency']
        tm = tmp.as_matrix()
        for i in range(tmp.count()):
            #print(tmp.as_matrix()[i])
            self.price.append(tm[i])

adnw_lst = set()
price_lst = {}
count_lst = {}
hit_or_miss_lst = {}

get = 0;

#データ　セット　初期化
for i in set((lst['winner_id'])):
    adnw = Adnw(i)
    adnw.set_price(lst)
    
    adnw_lst.add(adnw.id)
    price_lst[i] = adnw.price
    #print(i)
    count_lst[i] = 0
    hit_or_miss_lst[i] = 0.0
    
    #print(adnw.price)
    #print(price_lst[i][len(price_lst[i])-1])

print('normal get')
print(sum(lst['winner_bid_price_adv_currency']))

adnw_act = {}

def trial(try_num, adnw_lst, price_lst, count_lst, hit_or_miss_lst):
    get = 0.0
    
    for i in range(try_num):
        j = random.choice(list(adnw_lst),1)[0]
        #print(j)
        #print(count_lst[j])
        get += price_lst[j][count_lst[j]%len(price_lst[j])]
        adnw_act[j].append(price_lst[j][count_lst[j]%len(price_lst[j])])
        #print(j)
        #print(adnw_act[j])
        count_lst[j] += 1
        hit_or_miss_lst[j] = count_lst[j] / (i + 1)
    return get

print('rondom get')
try_num = 100
print(trial(try_num, adnw_lst, price_lst, count_lst, hit_or_miss_lst))

print("kari")
print(adnw_lst)
print("jissai")
#print(adnw_act[2][4])
print("count")
print(count_lst)

"""
sum_count = 0

for j in set(adnw_lst):
    sum_count += count_lst[j]

print(sum_count)
"""

argmax(adnw_act)
adnw_act

normal get
0.4409263879999992
rondom get

KeyError: 30

In [297]:
adnw1 = Adnw(1)
adnw1.set_price(lst)
print(adnw1.price)

adnw2= Adnw(2)
adnw2.set_price(lst)
print(adnw2.price)

[0.001, 0.001, 0.001, 0.001]
[0.00125, 0.002, 0.00125, 0.00125, 0.002, 0.001, 0.001, 0.00125, 0.002]